### ISSUE TITLE
change the exports ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/xy-parser#1]
@targos 

Should we change the code so that we exports directly the parser ?

**Comment by targos** [comment]
If you are confident that there will never be another export in this project, go ahead !

To stay backward-compatible, you can do it like this:

```js
function parseXY(...){
  ...
}

parseXY.parse = parseXY; // keep compatibility
module.exports = parseXY; // direct export
```

**Comment by targos** [comment]
In fact make the change it anyway. If we add another export, we can do it like the compatibility line
